### ISSUE TITLE
Lists don't "end" after 2 blank lines

### ISSUE THREAD

**Issue by mrjbq7** [fletcher/MMD-Test-Suite#8]
The [CommonMark spec](http://spec.commonmark.org/) says:

"A [list](http://spec.commonmark.org/0.26/#list) is a sequence of one or more list items [of the same type](http://spec.commonmark.org/0.26/#of-the-same-type). The list items may be separated by single [blank lines](http://spec.commonmark.org/0.26/#blank-line), but two blank lines end all containing lists."

That doesn't seem to be the case, as this example where an ordered list follows an unordered list with several blank lines:

```
* bullet
* bullet
* bullet



1. one
2. two
3. three
```

Turns into this:

```
<ul>
<li><p>bullet</p></li>
<li><p>bullet</p></li>
<li><p>bullet</p></li>
<li><p>one</p></li>
<li><p>two</p></li>
<li><p>three</p></li>
</ul>
```

Instead of this expected result:

```
<ul>
<li><p>bullet</p></li>
<li><p>bullet</p></li>
<li><p>bullet</p></li>
</ul>
<ol>
<li><p>one</p></li>
<li><p>two</p></li>
<li><p>three</p></li>
</ol>
```

**Comment by mrjbq7** [comment]
I should also note that MultiMarkdown fails several of the list test cases mentioned in the lists section of the CommonMark 0.26 specification (examples 262, 263, and 264):

http://spec.commonmark.org/0.26/#example-262

**Comment by mrjbq7** [comment]
It is possible that the "of the same type" is the root of the bug, because of example 267, where multiple blank lines do not end the list:

http://spec.commonmark.org/0.26/#example-267

**Comment by fletcher** [comment]
MultiMarkdown is based on Markdown, not CommonMark (which MultiMarkdown predates by many years).  This is not a bug, or a failure of tests, but a difference of design between the two projects.

CommonMark gets many things right.  Some things, I believe, it gets wrong.

For various reasons, which have been discussed ad nauseum over the years, this will not be changed now, as it is not a bug.  This behavior *may or may not* change in future versions of MultiMarkdown.

**Comment by mrjbq7** [comment]
@fletcher Okay, well thank you for looking into this.  I guess I had seen some "CommonMark" tests in this suite and thought this (and most other Markdown implementations) would be moving to standardize.

Do you have a specification for "MultiMarkdown" anywhere?  Or is it specified mainly by its implementation and test suite?

The reason I filed this bug was that I am using ``iA Writer.app`` and it rendered some of my text files in ways I was not expecting.  They apparently embed MultiMarkdown and pointed me to https://fletcher.github.io/MultiMarkdown-5/ which didn't seem to provide a specification so much as a general description of "Gruber Markdown.pl + Unspecified Different Behavior" (for example, formatting ``my_long_variable`` differently).
